# Generated by Django 4.1.12 on 2023-11-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_faculty_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
